{{ Html::script('js/jquery.min.js') }}
{{ Html::script('js/bootstrap.min.js') }}
{{ Html::script('js/fastclick.js') }}
{{ Html::script('js/adminlte.min.js') }}
{{ Html::script('js/jquery.sparkline.min.js') }}
{{ Html::script('js/jquery-jvectormap-1.2.2.min.js') }}
{{ Html::script('js/jquery-jvectormap-world-mill-en.min.js') }}
{{ Html::script('js/jquery.slimscroll.min.js') }}
{{ Html::script('js/Chart.min.js') }}
